### ISSUE TITLE
missing logic for VWAP

### ISSUE THREAD

**Issue by iSkywalker168** [MerlinR/Hexital#19]
thank you for the project.  love it very much.
I found one issue, could you please fix it?
vwap from pandas_ta will reset volume for each day(can pass in as parameter, timeframe can be month, week, hour or other timeframe), but Hexital vwap won't.

<img width="1691" alt="2214E36F-0B5A-44a7-B824-63202A134C8E" src="https://github.com/user-attachments/assets/e1129ec2-fe50-4d92-ad4f-edfbd40151ab">

**Comment by MerlinR** [comment]
Hey @iSkywalker168,

Sorry for slow reply, I glad you enjoying the library! Welcome to add more issue's of missing/useful features.

Yeah I can add this feature in! I'll add to the development branch, Currently the development branch is a fair abit ahead and will move to Master soon for new release.

**Comment by iSkywalker168** [comment]
can't help to try the new release, your work is much valuable to real-time trading.

besides, after contrasting Hexital with pandas_ta, I found that Hexital calculating RMA correctly(using the right formula), but not pandas_ta.
and the development branch of pandas_ta still got wrong result of RMA, https://github.com/twopirllc/pandas-ta/issues/402

thank you again for the great work.

**Comment by MerlinR** [comment]
I appreciate feedback!

I have had issue's testing directly against Pandas-TA due to some differences in results even when i believe my solution is accurate, often it's due to initial reading's differ while all following readings are correct, which is why in the `test_indicators` file I can specifically define how many results to validate against.

This is also why I had my testing if failed to 100% match Pandas-TA to then test my results and Pandas-TA with a correlation coefficient, to ensure that while the results may differ the resulting values still follow the same trend.


However, in the Dev branch I have removed the correlation coefficient as it would pass results that followed same trend but differ massively, I have also swapped from Deepdiff that rounded results causing incorrect failure points for a custom solution. Im still not 100% happy with the testing method, and looking at QuanTAlib this may be the best approach going forward, im going to continue to experiment with best testing method's as I dont trust my maths alone and need some reference as a source of truth.

**Comment by iSkywalker168** [comment]
`from pandas_ta import hlc3


class IncrementalVWAP:
    def __init__(self, anchor="D"):
        self.anchor = anchor.upper()
        self.reset()

    def reset(self):
        self.cumulative_wp = 0
        self.cumulative_volume = 0
        self.last_period = None
        self.vwap = None

    def update(self, timestamp, high, low, close, volume):
        typical_price = (high + low + close) / 3.0
        current_period = timestamp.to_period(self.anchor)

        if self.last_period != current_period:
            self.last_period = current_period
            self.cumulative_wp = 0
            self.cumulative_volume = 0

        wp = typical_price * volume
        self.cumulative_wp += wp
        self.cumulative_volume += volume

        if self.cumulative_volume != 0:
            self.vwap = self.cumulative_wp / self.cumulative_volume
        else:
            self.vwap = None

        return self.vwap
`

`vwap_calculator = IncrementalVWAP.IncrementalVWAP(anchor='D')
vwap_value = vwap_calculator.update(timestamp=candle.timestamp, high=candle.high, low=candle.low, close=candle.close, volume=candle.volume)
`

here is an incremental VWAP version which gets identical results with pandas_ta, please have a check, and integrate it into Hexital

**Comment by MerlinR** [comment]
Hey. @iSkywalker168 

I have already completed a incremental VWAP which is within the Development branch, I had been putting of pushing to remote (github) because I have also altered my testing setup which shows _MACD_ and _ADX_ being slightly off and failing unit tests. I have no pushed so if you wished to use  incremental VWAP you would need to use the development branch, I will create a new release once I have resolved these issues.

I appreciate the work, you put into creating the incremental VWAP, in fact logic wise it's identical to the version I have commited. A few notes for future collaboration commits!

- This library does not use Numpy/Pandas
  - So using hlc3 or `timestamp.to_period` is not an option, my `timestamp.to_period` method is closest alternative.
- Somewhat counter intuitively, this library store's **all** incrementally required variables inside the Candle's themselves.

I typical create a `Managed` indicator which i use to store related information, the purpose of this is to detach the required data for calculation from the objects. This means you can export the candles to a DB, re-import them and continue calculating incrementally where it was left off rather than re-calculating everything.

You can see this being used in the updated [VWAP](https://github.com/MerlinR/Hexital/blob/development/hexital/indicators/vwap.py)

If your want to test the anchor VWAP you can download it directly from the development branch with:
`pip install git+https://github.com/merlinr/hexital.git@development`

**Comment by iSkywalker168** [comment]
appreciate your work. i will test the develop branch~
